return {}
-- return {
--   "saghen/blink.cmp",
--   lazy = false, -- lazy loading handled internally
--   -- optional: provides snippets for the snippet source
--   dependencies = "rafamadriz/friendly-snippets",
--
--   -- use a release tag to download pre-built binaries
--   version = "v0.*",
--   -- OR build from source, requires nightly: https://rust-lang.github.io/rustup/concepts/channels.html#working-with-nightly-rust
--   -- build = 'cargo build --release',
--   -- If you use nix, you can build from source using latest nightly rust with:
--   -- build = 'nix run .#build-plugin',
--
--   opts = {
--     -- 'default' for mappings similar to built-in completion
--     -- 'super-tab' for mappings similar to vscode (tab to accept, arrow keys to navigate)
--     -- 'enter' for mappings similar to 'super-tab' but with 'enter' to accept
--     -- see the "default configuration" section below for full documentation on how to define
--     -- your own keymap.
--     keymap = {
--       preset = "enter",
--       ["<C-e>"] = { "hide", "show", "fallback" },
--       ["<Tab>"] = { "select_next", "fallback" },
--       ["<S-Tab>"] = { "select_prev", "fallback" },
--       ["<C-l>"] = { "snippet_forward", "fallback" },
--       ["<C-h>"] = { "snippet_backward", "fallback" },
--     },
--
--     sources = {
--       -- add lazydev to your completion providers
--       completion = {
--         enabled_providers = { "lsp", "path", "snippets", "buffer", "lazydev" },
--       },
--       providers = {
--         -- dont show LuaLS require statements when lazydev has items
--         lsp = { fallback_for = { "lazydev" } },
--         lazydev = { name = "LazyDev", module = "lazydev.integrations.blink" },
--       },
--     },
--
--     highlight = {
--       -- sets the fallback highlight groups to nvim-cmp's highlight groups
--       -- useful for when your theme doesn't support blink.cmp
--       -- will be removed in a future release, assuming themes add support
--       -- use_nvim_cmp_as_default = true,
--     },
--
--     -- experimental auto-brackets support
--     -- accept = { auto_brackets = { enabled = true } }
--
--     -- experimental signature help support
--     trigger = { signature_help = { enabled = true } },
--     windows = {
--       autocomplete = {
--         selection = "manual",
--       },
--       documentation = {
--         auto_show = true,
--       },
--     },
--   },
-- }
